# Generated by Django 4.0.3 on 2023-04-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_monitor',
            field=models.BooleanField(default=False),
        ),
    ]
