# Generated by Django 4.0.3 on 2023-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='top_fixed',
            field=models.BooleanField(default=False, verbose_name='top_fix'),
        ),
    ]
